# Generated by Django 4.2.30 on 2026-09-10 04:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_path', models.TextField(help_text='Absolute path to the local git repository')),
                ('base_ref', models.CharField(max_length=256)),
                ('target_ref', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_diff', models.TextField(blank=True, default='')),
                ('errors', models.JSONField(blank=True, default=list)),
                ('review_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.TextField()),
                ('line', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('evidence', models.TextField()),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='llm', max_length=32)),
                ('feedback', models.CharField(choices=[('none', 'None'), ('accept', 'Accept'), ('dismiss', 'Dismiss')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.review')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
