# Generated by Django 4.2.30 on 2026-09-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfinding',
            name='reviewer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewfinding',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
