# Generated by Django 4.2.30 on 2026-09-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewfinding_reviewer_reviewfinding_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_latency_ms', models.IntegerField(default=0)),
                ('total_estimated_cost', models.FloatField(blank=True, null=True)),
                ('llm_calls', models.IntegerField(default=0)),
                ('models_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='LLMCallUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('estimated_cost', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_usage', to='reviews.review')),
            ],
        ),
    ]
