# Generated by Django 4.2.30 on 2026-09-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewusage_llmcallusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewusage',
            name='iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='tool_calls',
            field=models.IntegerField(default=0),
        ),
    ]
