# Generated by Django 4.2.30 on 2026-09-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewusage_iterations_reviewusage_tool_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewusage',
            name='iterations',
        ),
        migrations.RemoveField(
            model_name='reviewusage',
            name='tool_calls',
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='agent_iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='critical_path_latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='duplicate_mcp_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='fallback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='finalization_reason',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='langgraph_node_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='llm_latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='mcp_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='mcp_latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='timeout_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewusage',
            name='unique_mcp_calls',
            field=models.IntegerField(default=0),
        ),
    ]
