# Generated by Django 4.2.30 on 2026-09-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_reviewusage_iterations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcallusage',
            name='diff_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='history_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='phase',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='reviewer_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='source_code_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='structured_schema_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='system_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='tool_result_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmcallusage',
            name='tool_schema_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
